version: '3'

 
services:
  db:
    image: postgres:13.1
    container_name: nextcloud_postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gXtRx9JZxWTWp3
      - POSTGRES_DB=nextcloud
      - APP_DB_USER=przemek
      - APP_DB_PASS=J6mhrL2hnqs77J
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - /nextcloud/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: ./nextcloud_dockerfile
    container_name: nextcloud_app
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
    links:
      - db
    volumes:
      - /nextcloud/nextcloud:/var/www/html
      #- ./apache:/etc/apache2/sites-enabled
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=przemek
      - POSTGRES_HOST=nextcloud_postgres:5432
