version: '3'

 
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    networks:
      nextcloud_network:
        ipv4_address: 172.22.0.2
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./main_webpage:/usr/share/nginx/html
  
  db:
    image: postgres:13.1
    container_name: nextcloud_postgres
    restart: always
    networks:
      nextcloud_network:
        ipv4_address: 172.22.0.3
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=nextcloud
      - APP_DB_USER=przemek
    env_file:
     - env_secrets.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - /nextcloud/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: nextcloud
    container_name: nextcloud_app
    restart: always
    networks:
      nextcloud_network:
        ipv4_address: 172.22.0.4
    depends_on:
      - db
      - nginx
    links:
      - db
    volumes:
      - /nextcloud/nextcloud:/var/www/html
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=przemek
      - POSTGRES_HOST=nextcloud_postgres:5432


networks:
  nextcloud_network:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16